package org.hilel14.filedeck.de.gui;

import java.awt.Desktop;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import org.hilel14.filedeck.de.Config;

/**
 *
 * @author hilel14
 */
public class SettingsDialog extends javax.swing.JDialog {

    public static final Logger LOGGER = Logger.getLogger(SettingsDialog.class.getName());
    static Preferences preferences = Preferences.userNodeForPackage(SettingsDialog.class);
    final Config config;

    /**
     * Creates new form SettingsDialog
     *
     * @param parent
     * @param config
     */
    public SettingsDialog(java.awt.Frame parent, Config config) {
        super(parent, true);
        this.config = config;
        initComponents();
        loadPreferences();
        showSettings();
    }

    private void loadPreferences() {
        // frame size and location
        int x = preferences.getInt("SettingsDialog.left", 10);
        int y = preferences.getInt("SettingsDialog.top", 25);
        int w = preferences.getInt("SettingsDialog.width", 600);
        int h = preferences.getInt("SettingsDialog.height", 300);
        setBounds(x, y, w, h);
    }

    private void storePreferences() {
        // frame size and location
        preferences.putInt("SettingsDialog.left", getBounds().x);
        preferences.putInt("SettingsDialog.top", getBounds().y);
        preferences.putInt("SettingsDialog.width", getBounds().width);
        preferences.putInt("SettingsDialog.height", getBounds().height);
    }

    private void showSettings() {
        appVersionTextField.setText(config.getAppVersion());
        rootFolderTextField.setText(config.getRootFolder().toString());
        evoJobsTextField.setText(config.getEvoFolder().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentPanel = new javax.swing.JPanel();
        appVersionLabel = new javax.swing.JLabel();
        appVersionTextField = new javax.swing.JTextField();
        rootFolderLabel = new javax.swing.JLabel();
        rootFolderTextField = new javax.swing.JTextField();
        evoJobsLabel = new javax.swing.JLabel();
        evoJobsTextField = new javax.swing.JTextField();
        litmusConfigurationLabel = new javax.swing.JLabel();
        litmusConfigurationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FileDeck Settings");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        contentPanel.setLayout(new java.awt.GridBagLayout());

        appVersionLabel.setText("FileDeck version");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(appVersionLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        contentPanel.add(appVersionTextField, gridBagConstraints);

        rootFolderLabel.setText("Root folder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(rootFolderLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        contentPanel.add(rootFolderTextField, gridBagConstraints);

        evoJobsLabel.setText("Evo jobs folder");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(evoJobsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        contentPanel.add(evoJobsTextField, gridBagConstraints);

        litmusConfigurationLabel.setText("Litmus configuration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(litmusConfigurationLabel, gridBagConstraints);

        litmusConfigurationButton.setText("Browse");
        litmusConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                litmusConfigurationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        contentPanel.add(litmusConfigurationButton, gridBagConstraints);

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        storePreferences();
    }//GEN-LAST:event_formWindowClosed

    private void litmusConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_litmusConfigurationButtonActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=lHDMn_ogRHU"));
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,
                    "The Litmus configuration is not supported on this machine",
                    "FileDeck Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_litmusConfigurationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JTextField appVersionTextField;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel evoJobsLabel;
    private javax.swing.JTextField evoJobsTextField;
    private javax.swing.JButton litmusConfigurationButton;
    private javax.swing.JLabel litmusConfigurationLabel;
    private javax.swing.JLabel rootFolderLabel;
    private javax.swing.JTextField rootFolderTextField;
    // End of variables declaration//GEN-END:variables
}
